server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

polyglot:

  core:
    enabled: true
    fail-fast: true
    log-metadata-on-startup: true
    log-level: debug

  python:
    enabled: true
    resources-path: classpath:python
    safe-defaults: true
    warmup-on-startup: true

  js:
    enabled: false
    
  actuator:
    info:
      enabled: true
    health:
      enabled: true

  metrics:
    enabled: true
